---EXPLORING ANIMAL HEALTH DATA FOR *DOMESTIC* ANIMALS SINCE 2005
---DATA RETRIEVED FROM OIE-WAHIS (WORLD ANIMAL HEALTH INFORMATION SYSTEM)
---ON 01/12/2022

---SKILLS USED: AGGREGATE FUNCTIONS, WINDOW FUNCTIONS, CTE, SUBQUERIES, CASE STATEMENT
		
--I. SEE TOTAL NUMBER OF RECORDS
			
	SELECT COUNT(*) FROM ANIMAL_HEALTH_REPORT;
					
--II. A GLANCE AT THE TOP 1000 RECORDS

	SELECT TOP 1000 * FROM ANIMAL_HEALTH_REPORT;

---A. SETTING THINGS UP

--I. SELECT COLUMNS WE WILL BE WORKING WITH
		
	SELECT  YEAR, WORLD_REGION, COUNTRY, SPECIES
	DISEASE, VACCINATED, CASES, NEW_OUTBREAKS,
	SUSCEPTIBLE, VACCINATED, KILLED_AND_DISPOSED_OF,
	SLAUGHTERED, DEATHS
	FROM ANIMAL_HEALTH_REPORT;

--II. CREATE TEMPORARY TABLE FOR THESE COLUMNS
			
	SELECT  YEAR, WORLD_REGION, COUNTRY, SPECIES,
	DISEASE, VACCINATED, CASES, NEW_OUTBREAKS, 
	SUSCEPTIBLE, KILLED_AND_DISPOSED_OF,
	SLAUGHTERED, DEATHS
	INTO #DOMESTIC_ANIMAL
	FROM ANIMAL_HEALTH_REPORT;

	SELECT * FROM #DOMESTIC_ANIMAL
	ORDER BY YEAR DESC;

---B. PARTIAL DATA EXPLORATION FOR REPORTED DISEASES AMONG DOMESTIC ANIMALS AROUND THE WORLD

--I. NUMBER OF DOMESTIC ANIMALS THAT HAVE LOST THEIR LIVES BY YEAR
			
	SELECT YEAR, 
	FORMAT(SUM(KILLED_AND_DISPOSED_OF), '###,###,###') AS KILLED_AND_DISPOSED_OF,
	FORMAT(SUM(SLAUGHTERED), '###,###,###') AS SLAUGHTERED, 
	FORMAT(SUM(DEATHS), '###,###,###') AS DEATHS,
	FORMAT(SUM(KILLED_AND_DISPOSED_OF + SLAUGHTERED + DEATHS), '###,###,###') AS TOTAL_LIVES_LOST
	FROM #DOMESTIC_ANIMAL
	GROUP BY YEAR
	ORDER BY 1 DESC;

	-- TOTAL LIVES LOST WITH PERCENT INCREASE/DECREASE BY YEAR

	WITH CTE1 AS
	( SELECT YEAR, 
		SUM(KILLED_AND_DISPOSED_OF + SLAUGHTERED + DEATHS)
		AS TOTAL_LIVES_LOST	
		FROM #DOMESTIC_ANIMAL
		GROUP BY YEAR ),
			CTE2 AS
	( SELECT *, LEAD(TOTAL_LIVES_LOST, 1) OVER (ORDER BY YEAR DESC) 
		AS PREVIOUS_NUMB
		FROM CTE1 )
	SELECT YEAR, TOTAL_LIVES_LOST,
	CAST(((TOTAL_LIVES_LOST - PREVIOUS_NUMB)/PREVIOUS_NUMB)*100 AS DEC(3,1))
	AS [PERCT_INCREASE/DECREASE]
	FROM CTE2;

	-- NUMBER OF DOMESTIC ANIMALS KILLED, SLAUGHTERED,
	-- OR DIED, BY REGION, BY YEAR
			
	WITH CTE AS ( SELECT YEAR,
	WORLD_REGION, SUM(KILLED_AND_DISPOSED_OF) KILLED_AND_DISPOSED_OF, 
	SUM(SLAUGHTERED) SLAUGHTERED, SUM(DEATHS) DIED,
	CASE
		WHEN LAG(YEAR, 1) OVER (PARTITION BY YEAR ORDER BY YEAR DESC ) =   -- WILL SKIP THE NEXT YEAR
		LAG(YEAR, 1) OVER (PARTITION BY YEAR ORDER BY YEAR DESC ) THEN ' ' -- WHEN THE PREVIOUS YEAR 
		ELSE YEAR														   														 -- IS THE SAME
	END AS YEAR_IN
		FROM #DOMESTIC_ANIMAL
		GROUP BY YEAR, WORLD_REGION )
	SELECT YEAR_IN AS YEAR, WORLD_REGION, KILLED_AND_DISPOSED_OF, SLAUGHTERED, DIED
	FROM CTE;

--II. TOTAL CASES OF DISEASES BY SPECIES THAT HAVE CONTRACTED THEM
--    OVER THE LAST 10 YEARS

	SELECT SPECIES, 
	SUM(CASES) TOTAL_CASES,
	SUM(KILLED_AND_DISPOSED_OF) AS KILLED_AND_DISPOSED_OF, 
	SUM(SLAUGHTERED) AS SLAUGHTERED, 
	SUM(DEATHS) AS DEATHS
	FROM #DOMESTIC_ANIMAL WHERE YEAR >= 2011
	GROUP BY SPECIES
	ORDER BY 2 DESC;

	--A LOOK AT THE LIST OF REPORTED DISEASES AND VACCINATION NUMBERS
	--IN 2020-2021 ALONE

	SELECT DISTINCT(DISEASE), 
	SUM(CASES) OVER (PARTITION BY DISEASE) AS TOTAL_CASES,
	SUM(VACCINATED) OVER (PARTITION BY DISEASE) AS TOTAL_VACCINATED
	FROM #DOMESTIC_ANIMAL
	WHERE YEAR IN (2020, 2021)
	ORDER BY 2 DESC;

--III. TOTAL NUMBER OF DOMESTIC ANIMALS KILLED AND DISPOSED OF, SLAUGHTERED,
-- AND DIED, BY REGION, SINCE 2005

	SELECT WORLD_REGION, 
	SUM(KILLED_AND_DISPOSED_OF) AS KILLED_AND_DISPOSED_OF, 
	SUM(SLAUGHTERED) AS SLAUGHTERED, SUM(DEATHS) AS DIED
	FROM #DOMESTIC_ANIMAL
	GROUP BY WORLD_REGION
	ORDER BY 2 DESC;

--IV. LIST OF DOMESTIC ANIMALS AFFECTED BY SARS-COV-2

	SELECT SPECIES, SUM(CASES) AS TOTAL_CASES, 
	SUM(NEW_OUTBREAKS) AS NEW_OUTBREAKS
	FROM #DOMESTIC_ANIMAL
	WHERE DISEASE LIKE '%SARS-CoV-2%'
	GROUP BY SPECIES
	ORDER BY 2 DESC;

	-- DOMESTIC ANIMAL MOST SUSCEPITBLE TO SARS-COV-2

	SELECT TOP 1 SPECIES, 
	SUM(SUSCEPTIBLE) AS TOTAL_SUSCEPTIBLE 
	FROM #DOMESTIC_ANIMAL
	WHERE DISEASE LIKE '%SARS-CoV-2%'
	GROUP BY SPECIES
	ORDER BY 2 DESC;

--V. SARS-COV-2 GLOBAL NUMBERS AMONG DOMESTIC ANIMALS BY YEAR

	SELECT YEAR, 
	SUM(CASES) AS CASES, 
	SUM(NEW_OUTBREAKS) AS NEW_OUTBREAKS,
	SUM(VACCINATED) AS VACCINATED
	FROM #DOMESTIC_ANIMAL
	WHERE DISEASE LIKE '%SARS-COV-2%'
	GROUP BY YEAR
	ORDER BY YEAR DESC;

	-- SARS-COV-2 GLOBAL NUMBERS AMONG DOMESTIC ANIMALS BY REGION
			
	SELECT WORLD_REGION, 
	SUM(CASES) TOTAL_CASES
	FROM #DOMESTIC_ANIMAL
	WHERE DISEASE LIKE '%SARS-COV-2%'
	GROUP BY WORLD_REGION
	ORDER BY 2 DESC;
	
---C. PARTIAL DATA EXPLORATION FOR REPORTED DISEASES AMONG DOGS

--I. TOTAL NUMBER OF DOGS KILLED AND DISPOSED OF, SLAUGHTERED,
-- OR DIED DUE TO DISEASES BY YEAR

	SELECT YEAR, 
	SUM(KILLED_AND_DISPOSED_OF) KILLED_AND_DISPOSED_OF, 
	SUM(SLAUGHTERED) SLAUGHTERED, SUM(DEATHS) DEATHS
	FROM #DOMESTIC_ANIMAL
	WHERE SPECIES LIKE '%DOGS%'
	GROUP BY YEAR
	ORDER BY 1 DESC;

	-- TOTAL NUMBER OF DOGS THAT HAVE LOST THEIR LIVES BY REGION

	SELECT WORLD_REGION, 
	SUM(KILLED_AND_DISPOSED_OF + SLAUGHTERED + DEATHS) AS TOTAL_LIVES_LOST
	FROM #DOMESTIC_ANIMAL
	WHERE SPECIES LIKE '%DOGS%'
	GROUP BY WORLD_REGION
	ORDER BY TOTAL_LIVES_LOST DESC;

--II. MOST FREQUENT DISEASE AMONG DOGS BASED ON
--   NUMBER OF REPORTED CASES OVER THE LAST 10 YEARS

	SELECT TOP 1 DISEASE, SUM(CASES) TOTAL_CASES
	FROM #DOMESTIC_ANIMAL
	WHERE SPECIES LIKE '%DOGS%' AND YEAR >= 2011
	GROUP BY DISEASE
	ORDER BY TOTAL_CASES DESC;
							
					--- OR ---
			
	WITH CTE AS (
		SELECT DISEASE, SUM(CASES) TOTAL_CASES
		FROM #DOMESTIC_ANIMAL
		WHERE SPECIES LIKE '%DOGS%' AND YEAR >= 2011
		GROUP BY DISEASE
				)
	SELECT DISEASE, TOTAL_CASES FROM CTE
	WHERE TOTAL_CASES = (SELECT MAX(TOTAL_CASES) FROM CTE);

--III. LIST OF REPORTED DISEASES AMONG DOGS IN 2020-2021
			
	SELECT DISTINCT(DISEASE), 
	SUM(CASES) OVER (PARTITION BY DISEASE) TOTAL_CASES,
	SUM(NEW_OUTBREAKS) OVER (PARTITION BY DISEASE) NEW_OUTBREAKS
	FROM #DOMESTIC_ANIMAL
	WHERE SPECIES LIKE '%DOGS%' AND YEAR IN (2020, 2021)
	ORDER BY TOTAL_CASES DESC;

--IV. COMPARE SARS-COV-2 WITH RABIES VIRUS AMONG DOGS IN 2020-2021

	SELECT DISEASE,
	SUM(CASES) AS TOTAL_CASES,
	SUM(NEW_OUTBREAKS) AS NEW_OUTBREAKS
	FROM #DOMESTIC_ANIMAL
	WHERE (YEAR IN (2020, 2021) AND SPECIES LIKE '%DOGS%') AND
	(DISEASE LIKE '%Rabies virus%' OR DISEASE LIKE '%SARS-CoV-2%') AND
	(CASES <> 0)
	GROUP BY DISEASE;		

--V. SARS-COV-2 OVERVIEW AMONG DOGS BY YEAR
			
	SELECT YEAR,
	SUM(CASES) AS TOTAL_CASES,
	SUM(NEW_OUTBREAKS) AS NEW_OUTBREAKS
	FROM #DOMESTIC_ANIMAL
	WHERE SPECIES LIKE '%DOGS%' AND DISEASE LIKE '%SARS-COV-2%'
	GROUP BY YEAR;

--VI. CASES OF SARS-COV-2 AMONG DOGS BY COUNTRY
			
	SELECT COUNTRY,
	SUM(CASES) AS TOTAL_CASES
	FROM #DOMESTIC_ANIMAL
	WHERE SPECIES LIKE '%DOGS%' AND DISEASE LIKE '%SARS-COV-2%'
	GROUP BY COUNTRY
	ORDER BY 2 DESC;

	-- COUNTRY WITH MOST CASES FOR SARS-COV-2 AMONG DOGS

	SELECT TOP 1 COUNTRY,
	SUM(CASES) AS TOTAL_CASES
	FROM #DOMESTIC_ANIMAL
	WHERE SPECIES LIKE '%DOGS%' AND DISEASE LIKE '%SARS-COV-2%'
	GROUP BY COUNTRY
	ORDER BY 2 DESC;


												--- END ---
